### ISSUE TITLE
2 errors and then stuck

### ISSUE THREAD

**Issue by mrkoct92** [5cover/WinClean#13]
[dism.log](https://github.com/5cover/WinClean/files/13640424/dism.log)
Hello there.

I got an error "could not enumerate service pack on machine"
(log file attached)

also got a cross on "clear file explorer history"

C:\Program Files\WinClean>del /F /Q /A C:\Users\DELL\AppData\Roaming\Microsoft\Windows\Recent\* 

C:\Program Files\WinClean>del /F /Q /A C:\Users\DELL\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\* 

C:\Program Files\WinClean>del /F /Q /A C:\Users\DELL\AppData\Roaming\Microsoft\Windows\Recent\CustomDestinations\* 

C:\Program Files\WinClean>reg delete HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\RunMRU /VA /F 
The operation completed successfully.

C:\Program Files\WinClean>reg delete HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths /VA /F 

and then it got stuck at the 4th script out of 20 which was delete junk files

**Comment by 5cover** [comment]
Hello,

For the service packs, yes that's normal, Windows 10 systems don't usually support it.

The "Clear file explorer history" can fail due to a permissions issue.

For the "Delete junk files" script, the problem could come from the fact that it's trying to remove junk files on a distant network drive. Do you have such drives ?

In that case, the solution would be to make the "Delete junk files" script only target local drives.

Thanks for the feedback!

**Comment by mrkoct92** [comment]
After all other tasks completed, I tried the particular task again and then
it worked 👍
